### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by suhailms** [tudoanh/get_fshare#12]
Hi @tudoanh 

I'm getting some token error while running the script:

```
Traceback (most recent call last):
  File "D:/script/folder/fshare.py", line 6, in <module>
    bot.login()
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\get_fshare\get_fshare.py", line 34, in login
    self.token = login_data['token']
KeyError: 'token'
```

**Comment by tyrion9** [comment]
Change link `api.fshare.vn` to `api2.fshare.vn`
