### ISSUE TITLE
lỗi không login được dùng api

### ISSUE THREAD

**Issue by leephuong19** [tudoanh/get_fshare#14]
hiện tại mình đang gặp một lỗi là không pass được qua login để lấy token:

lỗi như bên dưới:

Traceback (most recent call last):
  File "fshare_test.py", line 6, in <module>
    bot.login()
  File "/usr/local/lib/python3.6/dist-packages/get_fshare/get_fshare.py", line 32, in login
    login_data = json.loads(response.read().decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

khi đặt để in kết quả: 
        login_request = conn.request('POST', '/api/user/login/', body=json.dumps(data))
        print("loglogin")
        print(login_request)
        response = conn.get_response(login_request)
        print("response")
        print(response)
        login_data = json.loads(response.read().decode('utf-8'))
kết quả: 

loglogin
1
response
<hyper.http20.response.HTTP20Response object at 0x7fcb2d83d198>
Traceback (most recent call last):

**Comment by tudoanh** [comment]
Đã dùng lib khác để request và phát hiện ra giờ API chỉ dành cho account VIP. Mình ko có acc vip nên ko test được xa hơn.

**Comment by tudoanh** [comment]
Đã fix
