### ISSUE TITLE
We should include a timeout so server can response

### ISSUE THREAD

**Issue by haindvn** [tudoanh/get_fshare#9]
Please refer to this repo, I used you API for download file and folder from FShare.

https://github.com/haindvn/FShareDownloader

In the code, this line sometime will result in error since FShare server can not respond as fast as we wish, please include some timeout tolerance i.e. **5 seconds**

The script will probably fail ~ 20~30% with the timeout

`conn = HTTPConnection('api.fshare.vn:443')`

```
 File "/usr/local/lib/python3.7/dist-packages/get_fshare/get_fshare.py", line 31, in login
    response = conn.get_response(login_request)
  File "/usr/local/lib/python3.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hyper/http20/connection.py", line 312, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/usr/local/lib/python3.7/dist-packages/hyper/http20/stream.py", line 230, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/usr/local/lib/python3.7/dist-packages/hyper/http20/connection.py", line 771, in _recv_cb
    self._single_read()
  File "/usr/local/lib/python3.7/dist-packages/hyper/http20/connection.py", line 665, in _single_read
    self._sock.fill()
  File "/usr/local/lib/python3.7/dist-packages/hyper/common/bufsocket.py", line 167, in fill
    count = self._sck.recv_into(self._buffer_view[self._buffer_end:])
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by phamvanhai208** [comment]
e bị lỗi như bên dưới sữa sao vậy ạ

Traceback (most recent call last):
  File "/content/FShareDownloader/fdownload.py", line 259, in <module>
    main()
  File "/content/FShareDownloader/fdownload.py", line 38, in main
    login_credential = configuration_read(CONFIG_FILE)
  File "/content/FShareDownloader/fdownload.py", line 203, in configuration_read
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.ini'
